[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
upload_port = /dev/ttyACM0
upload_speed = 115200
monitor_port = /dev/ttyACM0
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
  gilmaimon/ArduinoWebsockets @ ^0.5.4
  adafruit/Adafruit SSD1306 @ ^2.5.0
