CREATE TABLE teachers(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE auth_sessions(sid TEXT PRIMARY KEY,data TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE INDEX auth_expiry ON auth_sessions(expires);
CREATE TABLE classes(id TEXT PRIMARY KEY,owner_teacher_id TEXT NOT NULL REFERENCES teachers(id),name TEXT NOT NULL,archived INTEGER NOT NULL DEFAULT 0);
CREATE TABLE students(id TEXT PRIMARY KEY,class_id TEXT NOT NULL REFERENCES classes(id),student_code TEXT NOT NULL,full_name TEXT NOT NULL,UNIQUE(class_id,student_code));
CREATE TABLE question_banks(id TEXT PRIMARY KEY,owner_teacher_id TEXT NOT NULL REFERENCES teachers(id),name TEXT NOT NULL,subject TEXT NOT NULL DEFAULT '');
CREATE TABLE questions(id TEXT PRIMARY KEY,bank_id TEXT NOT NULL REFERENCES question_banks(id),data TEXT NOT NULL);
CREATE INDEX questions_bank ON questions(bank_id);
CREATE TABLE devices(id TEXT PRIMARY KEY,owner_teacher_id TEXT NOT NULL REFERENCES teachers(id),label TEXT NOT NULL,secret_hash TEXT NOT NULL,revoked INTEGER NOT NULL DEFAULT 0,last_seen INTEGER);
CREATE TABLE quiz_sessions(id TEXT PRIMARY KEY,owner_teacher_id TEXT NOT NULL REFERENCES teachers(id),class_id TEXT NOT NULL REFERENCES classes(id),bank_id TEXT NOT NULL REFERENCES question_banks(id),class_name TEXT NOT NULL,name TEXT NOT NULL,room_code TEXT NOT NULL,config TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'LOBBY',state_version INTEGER NOT NULL DEFAULT 0,current_order INTEGER NOT NULL DEFAULT 0,next_transition_at INTEGER,transition_remaining INTEGER,paused_at INTEGER,created_at INTEGER NOT NULL,finished_at INTEGER,early_finish INTEGER NOT NULL DEFAULT 0);
CREATE UNIQUE INDEX one_active_room ON quiz_sessions((1)) WHERE state IN ('RUNNING','PAUSED');
CREATE TABLE session_students(id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES quiz_sessions(id),student_id TEXT NOT NULL,student_code TEXT NOT NULL,full_name TEXT NOT NULL,absent INTEGER NOT NULL DEFAULT 0,UNIQUE(session_id,student_id));
CREATE TABLE session_devices(id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES quiz_sessions(id),session_student_id TEXT NOT NULL REFERENCES session_students(id),device_id TEXT NOT NULL REFERENCES devices(id),active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE UNIQUE INDEX binding_student ON session_devices(session_student_id) WHERE active=1;
CREATE UNIQUE INDEX binding_device ON session_devices(device_id) WHERE active=1;
CREATE TABLE session_questions(id TEXT PRIMARY KEY,session_id TEXT NOT NULL REFERENCES quiz_sessions(id),question_order INTEGER NOT NULL,data TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING',opened_at INTEGER,deadline_at INTEGER,closed_at INTEGER,remaining_ms INTEGER,pause_ms INTEGER NOT NULL DEFAULT 0,voided INTEGER NOT NULL DEFAULT 0,void_reason TEXT,UNIQUE(session_id,question_order));
CREATE TABLE answers(session_question_id TEXT NOT NULL REFERENCES session_questions(id),session_student_id TEXT NOT NULL REFERENCES session_students(id),binding_id TEXT NOT NULL REFERENCES session_devices(id),choice TEXT NOT NULL,seq INTEGER NOT NULL,received_at INTEGER NOT NULL,response_ms INTEGER NOT NULL,PRIMARY KEY(session_question_id,session_student_id));
CREATE TABLE answer_receipts(binding_id TEXT NOT NULL REFERENCES session_devices(id),request_id TEXT NOT NULL,payload_hash TEXT NOT NULL,ack TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(binding_id,request_id));
CREATE TABLE session_events(id INTEGER PRIMARY KEY,session_id TEXT NOT NULL REFERENCES quiz_sessions(id),type TEXT NOT NULL,actor TEXT,detail TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE commands(session_id TEXT NOT NULL REFERENCES quiz_sessions(id),command_id TEXT NOT NULL,payload_hash TEXT NOT NULL,result TEXT NOT NULL,PRIMARY KEY(session_id,command_id));
CREATE TABLE access_tokens(hash TEXT PRIMARY KEY,kind TEXT NOT NULL,resource_id TEXT NOT NULL,owner_teacher_id TEXT NOT NULL REFERENCES teachers(id),auth_sid TEXT NOT NULL,expires INTEGER NOT NULL,used INTEGER NOT NULL DEFAULT 0);
